version: "3.8"

networks:
  caddy:

services:
  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./caddyfile.dev:/etc/caddy/Caddyfile:ro"
    networks:
      - caddy
    restart: always
    depends_on:
      - webapp

  webapp:
    container_name: webapp
    image: docker-compose-perfection/webapp:dev
    build:
      context: ./src/webapp
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "8000:8000"
    networks:
      - caddy
    
