# Environment arguments
ARG PROJECT_AUTHORS
ARG PROJECT_LICENSE
ARG PROJECT_SOURCES
ARG CONTAINER_PROXY_NAME
ARG CONTAINER_PROXY_DESCRIPTION
ARG CONTAINER_PROXY_SOURCE

# Caddy base image
ARG ALPINE_VERSION=3.18
ARG GO_VERSION=1.21.3
ARG CADDY_VERSION=v2.7.5

# ---- Build Stage ----
FROM golang:${GO_VERSION}-alpine${ALPINE_VERSION} AS builder
RUN apk add -q --progress --update --no-cache git ca-certificates tzdata
RUN mkdir -p /caddydir/data && \
    chmod -R 700 /caddydir
ENV GO111MODULE=on \
    CGO_ENABLED=0

RUN go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
WORKDIR /caddy

ARG PLUGINS=
RUN for plugin in $(echo $PLUGINS | tr "," " "); do withFlags="$withFlags --with $plugin"; done && \
    xcaddy build ${CADDY_VERSION} ${withFlags}

# ---- Final Stage ----
FROM alpine:${ALPINE_VERSION}

LABEL \
    com.timmypidashev.image.title=$CONTAINER_PROXY_NAME \
    com.timmypidashev.image.description=$CONTAINER_PROXY_DESCRIPTION \
    com.timmypidashev.image.authors=$PROJECT_AUTHORS \
    com.timmypidashev.license=$PROJECT_LICENSE \
    com.timmypidashev.image.url=$CONTAINER_PROXY_SOURCE \
    com.timmypidashev.image.source=$PROJECT_SOURCES

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo

EXPOSE 8080 8443 2015
ENV HOME=/caddydir \
    CADDYPATH=/caddydir/data \
    TZ=America/Los_Angeles

COPY --from=builder --chown=1000 /caddydir /caddydir

VOLUME ["/caddydir"]
ENTRYPOINT ["/caddy"]
USER 1000

# see https://caddyserver.com/docs/cli
COPY --chown=1000 Caddyfile.dev /caddydir/Caddyfile.dev
COPY --from=builder --chown=1000 /caddy/caddy /caddy
CMD ["run","--config","/caddydir/Caddyfile.dev"]
